### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by LonglongaaaGo** [aimagelab/FourBi_7#2]
Hi @quattrinifabio ，

Thanks for the awesome project!
I would like to know how I can download other training datasets. 
do you have links? 
Thank you so much!

**Comment by quattrinifabio** [comment]
Hi, thank you!

You can find the datasets on the web: 

- Nabuco + DIBCOs: https://dib.cin.ufpe.br/#!/datasets/datasets/real-documents
- Bickley diary: https://github.com/vqnhat/DSN-Binarization/files/2793688/original_gt_labeled.zip
- SMADI: https://tc11.cvc.uab.es/datasets/SMADI_1
- PHIBD: https://tc11.cvc.uab.es/datasets/PHIBD%202012_1
- ISOS-BTD: https://www.isos.dias.ie/Sigmedia/Bleed_Through_Database.html

**Comment by LonglongaaaGo** [comment]
Hi @quattrinifabio 
Thank you so much for the help!

**Comment by namectrl** [comment]
Hello, I would like to ask about the SMADI data set mentioned in the paper, did you train with all 8 different images? Still, only a few were selected for training
